name: Build Soviet Tarot Executables

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Build executable (Linux/Mac)
      if: runner.os != 'Windows'
      run: |
        pyinstaller --onefile --windowed --name "SovietTarotSystem" soviet_tarot_gui.py
        
    - name: Build executable (Windows)
      if: runner.os == 'Windows'
      run: |
        pyinstaller --onefile --windowed --name "SovietTarotSystem" soviet_tarot_gui.py
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SovietTarotSystem-${{ runner.os }}
        path: |
          dist/SovietTarotSystem*
